apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: killer-app-secrets
  namespace: killer-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: killer-app-secret
    creationPolicy: Owner
  data:
  - secretKey: SUPABASE_URL
    remoteRef:
      key: my-api-keys
      property: SUPABASE_URL
  - secretKey: SUPABASE_KEY
    remoteRef:
      key: my-api-keys
      property: SUPABASE_KEY
  - secretKey: SUPABASE_ANON_KEY
    remoteRef:
      key: my-api-keys
      property: SUPABASE_ANON_KEY
  - secretKey: GROQ_API_KEY
    remoteRef:
      key: my-api-keys
      property: GROQ_API_KEY    
